=== EnwardZuLiu/accumulation_java/src/main/resources/developer_platform.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://www.bioCloud.net/developer_platform.xsd"
           targetNamespace="http://www.bioCloud.net/developer_platform.xsd"
           elementFormDefault="qualified">
    <xs:element name="developer_platform">
        <xs:complexType>
            <xs:all>
                <xs:element ref="web_ui" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="data_nodes" minOccurs="1" maxOccurs="1"/>
            </xs:all>
        </xs:complexType>
        <xs:unique name="developer_platform_unique">
            <xs:selector xpath=".//*"/>
            <xs:field xpath="@id"/>
        </xs:unique>
        <!-- 外键约束，这里不需要存在外键约束 -->
        <!--<xs:key name="developer_platform_key">-->
            <!--<xs:selector xpath=".//*"/>-->
            <!--<xs:field xpath="@id"/>-->
        <!--</xs:key>-->
        <!--<xs:keyref refer="developer_platform_key" name="developer_platform_refer">-->
            <!--<xs:selector xpath=".//*"/>-->
            <!--<xs:field xpath="source"/>-->
        <!--</xs:keyref>-->
    </xs:element>
    <xs:element name="web_ui">
        <xs:complexType>
            <xs:sequence>
                <xs:choice maxOccurs="unbounded">
                    <xs:element ref="raw_data"/>
                    <xs:element ref="radios"/>
                    <xs:element ref="select"/>
                    <xs:element ref="group"/>
                    <xs:element ref="input"/>
                    <xs:element ref="difference_grouping"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="raw_data">
        <xs:complexType>
            <xs:all>
                <xs:element ref="label"/>
                <xs:element ref="description"/>
            </xs:all>
            <xs:attribute name="data_type" use="optional" default="fastq" type="xs:NCName"/>
            <xs:attribute name="data_format" use="optional" default="double">
                <xs:simpleType>
                    <xs:restriction base="xs:NCName">
                        <xs:enumeration value="double"/>
                        <xs:enumeration value="single"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="id" use="required" type="xs:NCName"/>
            <xs:attribute name="name" use="optional" type="xs:NCName"/>
            <xs:attribute name="order" use="required" type="xs:integer"/>
            <xs:attribute name="tab_name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="radios">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="label"/>
                <xs:element ref="description"/>
                <xs:element maxOccurs="unbounded" ref="radio"/>
            </xs:sequence>
            <xs:attribute name="id" use="required" type="xs:NCName"/>
            <xs:attribute name="name" use="optional" type="xs:NCName"/>
            <xs:attribute name="order" use="required" type="xs:integer"/>
            <xs:attribute name="tab_name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="radio">
        <xs:complexType mixed="true">
            <xs:attribute name="checked" type="xs:boolean"/>
            <xs:attribute name="name" use="optional" type="xs:string"/>
            <xs:attribute name="value" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="group">
        <xs:complexType>
            <xs:sequence>
                <xs:any maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="input">
        <xs:complexType>
            <xs:all>
                <xs:element ref="label"/>
                <xs:element ref="description"/>
                <xs:element ref="value"/>
            </xs:all>
            <xs:attribute name="disable" type="xs:boolean"/>
            <xs:attribute name="id" use="required" type="xs:NCName"/>
            <xs:attribute name="name" use="optional" type="xs:NCName"/>
            <xs:attribute name="order" use="required" type="xs:integer"/>
            <xs:attribute name="placeholder" type="xs:NCName"/>
            <xs:attribute name="tab_name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="value" type="xs:string"/>
    <xs:element name="difference_grouping">
        <xs:complexType>
            <xs:all>
                <xs:element ref="dependency"/>
                <xs:element ref="select_name_one"/>
                <xs:element ref="select_name_two"/>
                <xs:element ref="validation_rules"/>
            </xs:all>
            <xs:attribute name="id" use="required"/>
            <xs:attribute name="name" use="optional"/>
            <xs:attribute name="order" use="required" type="xs:integer"/>
            <xs:attribute name="tab_name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="dependency" type="xs:NCName"/>
    <xs:element name="select_name_one" type="xs:NCName"/>
    <xs:element name="select_name_two" type="xs:NCName"/>
    <xs:element name="validation_rules" type="xs:NCName"/>
    <xs:element name="data_nodes">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="data_node"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="data_node">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="1" minOccurs="0" ref="source"/>
            </xs:sequence>
            <xs:attribute name="classType">
                <xs:simpleType>
                    <xs:restriction base="xs:NCName">
                        <xs:enumeration value="boolean"/>
                        <xs:enumeration value="int"/>
                        <xs:enumeration value="string"/>
                        <xs:enumeration value="file"/>
                        <xs:enumeration value="File"/>
                        <xs:enumeration value="boolean_array"/>
                        <xs:enumeration value="int_array"/>
                        <xs:enumeration value="string_array"/>
                        <xs:enumeration value="File_Array"/>
                        <xs:enumeration value="directory"/>
                        <xs:enumeration value="directory_array"/>
                        <xs:enumeration value="filepath"/>
                        <xs:enumeration value="filepath_array"/>
                        <xs:enumeration value="files3key"/>
                        <xs:enumeration value="files3key_array"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="id" use="required" type="xs:NCName"/>
            <xs:attribute name="name" use="optional" type="xs:NCName"/>
            <xs:attribute name="parameterType" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:NCName">
                        <xs:enumeration value="value_class_size"/>
                        <xs:enumeration value="value_class"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="strategy" use="required" type="xs:NCName"/>
            <xs:attribute name="target" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:NCName">
                        <xs:enumeration value="metadata"/>
                        <xs:enumeration value="parameter_json"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="value" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="source" type="xs:NCName"/>
    <xs:element name="label" type="xs:string"/>
    <xs:element name="description" type="xs:string"/>
    <xs:element name="select">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="option"/>
            </xs:sequence>
            <xs:attribute name="dependency" type="xs:NCName"/>
            <xs:attribute name="id" use="required" type="xs:NCName"/>
            <xs:attribute name="name" use="optional" type="xs:NCName"/>
            <xs:attribute name="order" use="required" type="xs:integer"/>
            <xs:attribute name="tab_name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="option">
        <xs:complexType mixed="true">
            <xs:attribute name="selected" type="xs:boolean"/>
            <xs:attribute name="value" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== EnwardZuLiu/accumulation_java/src/test/resources/ref.xml
<?xml version="1.0" encoding="utf-8" ?>

<developer_platform xmlns="http://www.bioCloud.net/developer_platform.xsd"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://www.bioCloud.net/developer_platform.xsd developer_platform.xsd">

    <web_ui>
        <!-- 原始数据 -->
        <!--
            tab_name 表示选项卡的名称
            order 表示该元素在该选项卡的位置
            data_type 表示原始数据的数据类型
            data_format 标示原始数据是单端还是双端
         -->
        <radios id="qphred" name="qphred" order="3" tab_name="综合选项">
            <label>Qphred</label>
            <description>这里使用来显示说明文字的</description>

            <!--
                checked 表示该单选框是被默认选中的
             -->
            <radio checked="true" name="33">33</radio>
            <radio name="66" value="66"/>
        </radios>
        <raw_data id="raw" name="raw" order="1" tab_name="原始数据选择" data_type="fastq"
                  data_format="double">
            <label>原始数据</label>
            <description>这里选用的是fastq文件</description>
        </raw_data>

        <!-- 单选框组 -->
        <radios id="qphred1" name="qphred" order="3" tab_name="综合选项">
            <label>Qphred</label>
            <description>这里使用来显示说明文字的</description>

            <!--
                checked 表示该单选框是被默认选中的
             -->
            <radio checked="true" name="33">33</radio>
            <radio name="66" value="66"/>
        </radios>
        <input id="project_name1" name="project_name" order="2" tab_name="综合选项" disable="false"
               placeholder="请输入项目名称">
            <label>项目名称</label>
            <description>您能修改项目名称，但是只能输入中文、字母、数字、下划线，且50个字符以内。</description>

            <!-- 输入框的默认值，可以为空 -->
            <value>有参考基因组的转录组分析项目</value>
        </input>
        <radios id="lib_type" name="lib_type" order="4" tab_name="综合选项">
            <label>lib_type</label>
            <description>这里使用来显示说明文字的</description>
            <radio checked="true" name="fr-unstranded">fr-unstranded</radio>
            <radio name="fr-firststrand" value="fr-firststrand"/>
            <radio name="fr-secondstrand" value="fr-secondstrand"/>
        </radios>

        <!-- 文本输入框 -->
        <!--
            disable 表示用户是否可以修改
            placeholder 水印提示信息
         -->
        <input id="project_name2" name="project_name" order="2" tab_name="综合选项" disable="false"
               placeholder="请输入项目名称">
            <label>项目名称</label>
            <description>您能修改项目名称，但是只能输入中文、字母、数字、下划线，且50个字符以内。</description>

            <!-- 输入框的默认值，可以为空 -->
            <value>有参考基因组的转录组分析项目</value>
        </input>

        <!-- 下拉框 -->
        <select id="version1" name="version" order="1" tab_name="综合选项">
            <option selected="true" value="v2.0">v2.0</option>
            <option value="v1.0">v1.0</option>
        </select>

        <input id="project_name3" name="project_name" order="2" tab_name="综合选项" disable="false"
               placeholder="请输入项目名称">
            <label>项目名称</label>
            <description>您能修改项目名称，但是只能输入中文、字母、数字、下划线，且50个字符以内。</description>

            <!-- 输入框的默认值，可以为空 -->
            <value>有参考基因组的转录组分析项目</value>
        </input>

        <group>
            <select id="reference_species" name="reference_species" order="1" tab_name="基因功能注释">
                <option selected="true" value="Phaeodactylum_tricornutum">
                    三角褐指藻(Phaeodactylum_tricornutum)
                </option>
                <option value="Pichia_kudriavzevii">东方伊萨酵母(Pichia_kudriavzevii)</option>
                <option value="Pelodiscus_sinensis">中华鳖(Pelodiscus_sinensis)</option>
                <option value="Salvia_miltiorrhiza">丹参(Salvia_miltiorrhiza)</option>
                <option value="Gossypium_arboreum">亚洲棉(Gossypium_arboreum)</option>
                <option value="Pichia_and_Saccharomyces">伊萨_酿酒酵母(Pichia_and_Saccharomyces)</option>
            </select>
            <select id="species_version" name="version" order="2" tab_name="基因功能注释"
                    dependency="reference_species">
                <option selected="true">Phatr2</option>
            </select>
        </group>
        <select id="version5" name="version" order="1" tab_name="综合选项">
            <option selected="true" value="v2.0">v2.0</option>
            <option value="v1.0">v1.0</option>
        </select>

        <!-- 单选框 -->
        <input id="qphred3" name="qphred" order="1" tab_name="差异表达分析">
            <label>差异表达分析 FDR(False Discovery Rate)</label>
            <description>错误发现率，FDR阈值越低表示差异表达筛选越严格，筛选出来的差异表达结果越少，默认设置为0.01</description>
            <value>0.01</value>
        </input>
        <input id="qphred4" name="qphred" order="2" tab_name="差异表达分析">
            <label>差异筛选倍数阈值</label>
            <description>在对照组与实验组中，如果基因的表达量差异倍数超过此阈值，则认为该基因为差异表达的基因，默认设置为2</description>
            <value>2</value>
        </input>

        <!-- 差异分组 -->
        <difference_grouping id="differential_expression_analysis"
                             name="differential_expression_analysis" order="3"
                             tab_name="差异表达分析">
            <dependency>raw</dependency>
            <select_name_one>对照</select_name_one>
            <select_name_two>实验</select_name_two>
            <validation_rules>A</validation_rules>
        </difference_grouping>
    </web_ui>

    <data_nodes>
        <data_node id="databasePath" name="databasePath" strategy="base" parameterType="value_class"
                   target="metadata"
                   value="/share/biocloud-compute/genome_database">
        </data_node>
        <data_node id="AnnoDatabasePath" name="AnnoDatabasePath" strategy="base"
                   parameterType="value_class"
                   target="metadata" value="/share/biocloud-compute/anno_database">
        </data_node>
        <data_node id="project_name" name="project_name" strategy="base" parameterType="value_class"
                   target="parameter_json"
                   value="demo">
            <source>project_name</source>
        </data_node>
        <data_node id="projectId" name="projectId" strategy="base" parameterType="value_class"
                   target="metadata"
                   value="402888a3576951e201576952be4b0000"></data_node>
        <data_node id="version" name="version" strategy="base" parameterType="value_class"
                   target="metadata"
                   value="v2.0"></data_node>
        <data_node id="targetFolderUuid" name="targetFolderUuid" strategy="base"
                   parameterType="value_class"
                   target="metadata" value="89bc8442-a203-4ad2-bea6-46a6b890cba1"></data_node>

        <data_node id="Project_name" name="Project_id" strategy="base" parameterType="value_class"
                   classType="string"
                   target="parameter_json">
            <source>project_name</source>
        </data_node>
        <data_node id="Species" name="Species" strategy="base" parameterType="value_class"
                   classType="string"
                   target="parameter_json" value="Arabidopsis_thaliana"></data_node>
        <data_node id="Genome_version" name="Genome_version" strategy="base"
                   parameterType="value_class"
                   classType="string" target="parameter_json" value="TAIR10"></data_node>
        <data_node id="FDR" name="FDR" strategy="base" parameterType="value_class"
                   classType="string"
                   target="parameter_json" value="0.01"></data_node>
        <data_node id="fold" name="fold" strategy="base" parameterType="value_class"
                   classType="string"
                   target="parameter_json" value="2"></data_node>
        <data_node id="Download" name="Download" strategy="base" parameterType="value_class"
                   classType="string"
                   target="parameter_json"
                   value="ftp://ftp.genome.arizona.edu/pub/fpc/maize/"></data_node>
        <data_node id="sampleName" name="sampleName" strategy="base" parameterType="value_class"
                   classType="string_array" target="parameter_json"
                   value="T01,T02,T03,T04,T05,T06"></data_node>
        <data_node id="Com" name="Com" strategy="DifferenceGrouping" parameterType="value_class"
                   classType="string_array"
                   target="parameter_json">
            <source>differential_expression_analysis</source>
        </data_node>
        <data_node id="Sep" name="Sep" strategy="DifferenceGrouping" parameterType="value_class"
                   classType="string_array"
                   target="parameter_json">
            <source>differential_expression_analysis</source>
        </data_node>
        <data_node id="Project_key" name="Project_key" strategy="base" parameterType="value_class"
                   classType="string"
                   target="parameter_json" value="Arabidopsis_thaliana"></data_node>
        <data_node id="anno_db" name="anno_db" strategy="base" parameterType="value_class"
                   classType="string_array"
                   target="parameter_json"
                   value="/share/nas2/database/ncbi/Nt_Nr_division/nr_PLN,/share/nas2/database/kegg/kegg_divide/Plants.fa,/share/nas2/database/uniprot/knowledgebase/current/TrEMBL_Divide/uniprot_sprot_plants.fasta"></data_node>
        <data_node id="Lib_type" name="Lib_type" strategy="base" parameterType="value_class"
                   classType="string"
                   target="parameter_json" value="fr-unstranded"></data_node>
        <data_node id="r1_fqs" name="r1_fqs" strategy="RawData" parameterType="value_class_size"
                   classType="File_Array"
                   target="parameter_json">
            <source>raw</source>
        </data_node>
        <data_node id="r2_fqs" name="r2_fqs" strategy="RawData" parameterType="value_class_size"
                   classType="File_Array"
                   target="parameter_json">
